######################################################
#
# Example GNUmakefile to build an Application with Marlin
#
# @author Frank Gaede
# @date   Jun,11 2004
######################################################

#  copy to location of .cc files and edit the user variables

#---------- user variables ---------------------------------------------------

# name of the program
PROGNAME = Ganging


# path of Marlin
MARLIN = /afs/desy.de/user/g/gaede/public/Marlin/v00-01

# path of LCIO
LCIO = /products/lcio/v01-00
#LCIO = /afs/desy.de/user/g/gaede/public/lcio/v01-01beta_p01

# the base directory of your application
# this is where you  would normaly have the lib, bin and source directories
BASEDIR = .
INSTALL = $(BASEDIR)/lib
BINDIR = $(BASEDIR)/bin

#---------- user variables ---------------------------------------------------


# check for private compiler definition
ifdef MY_CXX
  CXX = $(MY_CXX)
else
  CXX = g++
endif

AR = ar


INCLUDE =  -I $(LCIO)/src/cpp/include
INCLUDE +=  -I $(MARLIN)/include
INCLUDE +=  -I $(BASEDIR)/include

CPPFLAGS += $(INCLUDE)
CPPFLAGS += -g -Wall -ansi

LIBS =    -L $(LCIO)/lib -llcio -L $(LCIO)/sio/lib -lsio -lz
LIBS +=   -Wl,-whole-archive  -L $(MARLIN)/lib  -lMarlin -Wl,-no-whole-archive
LIBS +=   -Wl,-whole-archive  -L $(INSTALL)  -l$(PROGNAME) -Wl,-no-whole-archive




bin:  lib $(BINDIR)/$(PROGNAME)



$(BINDIR)/$(PROGNAME): $(INSTALL)/lib$(PROGNAME).a
	$(CXX) -o $(BINDIR)/$(PROGNAME) $(CPPFLAGS) $(MARLIN)/src/Marlin.cc $(LIBS) 


objects = $(patsubst %.cc,%.o, $(wildcard *.cc)  )


$(INSTALL)/lib$(PROGNAME).a: $(objects)
	$(AR) cr $(INSTALL)/lib$(PROGNAME).a  $?

lib: $(INSTALL)/lib$(PROGNAME).a


clean:
	rm -f *.o $(INSTALL)/lib$(PROGNAME).a $(BINDIR)/$(PROGNAME)


