site_name: Marlin
nav:
    - Home: index.md
    - About:
      - License: 'about/license.md'
      - Contribute: 'about/contribute.md'
      - Citing Marlin: 'about/citing.md'
    - Documentation:
      - Doxygen: 'doxygen/index.html'
plugins:
  - doxygen:
      packages:
        - doxygen:
            url : doc/mkdoxygen
theme: readthedocs
