Marlin: marlin::SimpleScheduler Class Reference
marlin::SimpleScheduler Class Reference
SimpleScheduler class.
#include <SimpleScheduler.h>
Public Types
using Logger = Logging::Logger
using ProcessorSequence = std::shared_ptr< SuperSequence >
Public Member Functions
void init (Application *app)
Initialize the scheduler with app parameters.
void end ()
Terminate the scheduler activites Cleanup memory, etc ...
void processRunHeader (std::shared_ptr< EVENT::LCRunHeader > rhdr)
Process a run header.
void pushEvent (std::shared_ptr< EVENT::LCEvent > event)
Push a new event to the scheduler for processing.
void popFinishedEvents (std::vector< std::shared_ptr< EVENT::LCEvent >> &events)
Retrieve finished events from the scheduler.
std::size_t freeSlots () const
Get the number of free event slots.
Detailed Description
SimpleScheduler class.
Member Function Documentation
init()
void marlin::SimpleScheduler::init (Application * app) virtual
Initialize the scheduler with app parameters.
Parameters
app the application in which the scheduler runs
Implements marlin::IScheduler.
References marlin::Application::activeProcessors(), marlin::Application::createLogger(), and marlin::Application::processorParameters().
popFinishedEvents()
void marlin::SimpleScheduler::popFinishedEvents (std::vector< std::shared_ptr< EVENT::LCEvent >> & events) virtual
Retrieve finished events from the scheduler.
Parameters
events the list of event to retrieve
Implements marlin::IScheduler.
processRunHeader()
void marlin::SimpleScheduler::processRunHeader (std::shared_ptr< EVENT::LCRunHeader > rhdr) virtual
Process a run header.
Parameters
rhdr the run header to process
Implements marlin::IScheduler.
pushEvent()
void marlin::SimpleScheduler::pushEvent (std::shared_ptr< EVENT::LCEvent > event) virtual
Push a new event to the scheduler for processing.
Parameters
event the event to push
Implements marlin::IScheduler.
The documentation for this class was generated from the following files:
SimpleScheduler.h
SimpleScheduler.cc