Marlin: marlin::Logging Class Reference
marlin::Logging Class Reference
Logging class.
#include <Logging.h>
Public Types
using mutex_type = streamlog::st
using Logger = std::shared_ptr< streamlog::logstreamT< mutex_type > >
using StreamType = Logger::element_type::stream_type
Static Public Member Functions
static Logger createLogger (const std::string &name)
Create a standalone logger instance.
Detailed Description
Logging class.
Defines the basic logging functionalities in Marlin. For a more application oriented configuration, see LoggerManager.h
Member Function Documentation
createLogger()
Logging::Logger marlin::Logging::createLogger (const std::string & name) static
Create a standalone logger instance.
Parameters
name the logger name
Referenced by marlin::LoggerManager::createLogger(), marlin::DataSourcePlugin::DataSourcePlugin(), marlin::GeometryManager::GeometryManager(), marlin::GeometryPlugin::GeometryPlugin(), marlin::LoggerManager::LoggerManager(), and marlin::Processor::Processor().
The documentation for this class was generated from the following files:
Logging.h
Logging.cc