Marlin: marlin::IRecoParticleFactory Class Reference
marlin::IRecoParticleFactory Class Reference abstract
Interface for a factory class that creates a ReconstructedParticle from an MCParticle.
#include <IRecoParticleFactory.h>
Public Member Functions
virtual ~IRecoParticleFactory ()
Virtual d'tor.
virtual lcio::ReconstructedParticle * createReconstructedParticle (const lcio::MCParticle *mcp)=0
The actual factory method that creates a new ReconstructedParticle for the given MCParticle.
Detailed Description
Interface for a factory class that creates a ReconstructedParticle from an MCParticle.
Author
F. Gaede, DESY
Version
Id
IRecoParticleFactory.h,v 1.2 2005-10-11 12:56:28 gaede Exp
Constructor & Destructor Documentation
~IRecoParticleFactory()
virtual marlin::IRecoParticleFactory::~IRecoParticleFactory () inline virtual
Virtual d'tor.
References createReconstructedParticle().
Member Function Documentation
createReconstructedParticle()
virtual lcio::ReconstructedParticle* marlin::IRecoParticleFactory::createReconstructedParticle (const lcio::MCParticle * mcp) pure virtual
The actual factory method that creates a new ReconstructedParticle for the given MCParticle.
NULL if no ReconstructedParticle should be created due to detector acceptance.
Implemented in marlin::SimpleParticleFactory.
Referenced by marlin::SimpleFastMCProcessor::processEvent(), and ~IRecoParticleFactory().
The documentation for this class was generated from the following file:
IRecoParticleFactory.h