Marlin: marlin::ParameterT< T > Class Template Reference
marlin::ParameterT< T > Class Template Reference
ParameterT template class.
#include <Parameter.h>
Public Member Functions
ParameterT (const std::string &parameterName, const std::string &parameterDescription, T &parameter, const T &parameterDefaultValue, bool optional, int parameterSetSize=0)
Constructor.
const T & valueT () const
Get the parameter value.
const T & defaultValueT () const
Get the parameter default value.
const std::string type () const override
Get the parameter type as string.
const std::string defaultValue () const override
Get the parameter default value.
const std::string value () const override
Get the parameter value as string.
void setValue (StringParameters *params) override
Set the value using the string parameters.
Public Member Functions inherited from marlin::Parameter
const std::string & name () const
Get the parameter name.
const std::string & description () const
Get the parameter description.
int setSize () const
Get the set size (if the parameter is a vector)
bool isOptional () const
Whether the parameter is optional.
bool valueSet () const
Whether the value has been set during steering file parsing.
Protected Attributes
T & _value
The parameter value reference.
T _defaultValue
The default parameter value reference.
Protected Attributes inherited from marlin::Parameter
std::string _description {""}
The parameter description.
std::string _name {""}
The parameter name.
int _setSize {0}
The set size, if the parameter type is vector.
bool _optional {false}
Whether the parameter is optional.
bool _valueSet {false}
Whether the value has been set after parsing.
Detailed Description
template<typename T>
class marlin::ParameterT< T >
ParameterT template class.
Templated implementation of Parameter class.
Constructor & Destructor Documentation
ParameterT()
template<typename T > marlin::ParameterT< T >::ParameterT (const std::string & parameterName, const std::string & parameterDescription, T & parameter, const T & parameterDefaultValue, bool optional, int parameterSetSize = 0) inline
Constructor.
Parameters
parameterName the parameter name
parameterDescription the parameter description
parameter the parameter value reference
parameterDefaultValue the parameter default value
optional whether the parameter is optional while parsing the steering file
parameterSetSize the set size of the parameter, if of type vector
References marlin::Parameter::_description, marlin::Parameter::_name, marlin::Parameter::_optional, marlin::Parameter::_setSize, marlin::ParameterT< T >::_value, and marlin::Parameter::_valueSet.
Member Function Documentation
setValue()
template<typename T > void marlin::ParameterT< T >::setValue (StringParameters * params) override virtual
Set the value using the string parameters.
Parameters
params the string parameters to get the parameter value from
Implements marlin::Parameter.
References marlin::ParameterT< T >::_value, marlin::Parameter::_valueSet, marlin::StringParameters::get(), marlin::StringParameters::isParameterSet(), and marlin::Parameter::name().
The documentation for this class was generated from the following file:
Parameter.h