Marlin: marlin::GeometryManager Class Reference
marlin::GeometryManager Class Reference
GeometryManager class.
#include <GeometryManager.h>
Public Types
using Logger = Logging::Logger
Public Member Functions
GeometryManager (const GeometryManager &)=delete
GeometryManager & operator= (const GeometryManager &)=delete
GeometryManager ()
Default constructor.
void init (const Application *app)
Initialize the geometry manager.
template<typename T >
const T * geometry () const
Get the underlying geometry handle Example:
std::type_index typeIndex () const
Get the underlying geometry type info.
void clear ()
Clear the geometry content.
bool isInitialized () const
Whether the geometry has been initialized.
const Application & app () const
Get the application in which the manager is running Valid only after initialization.
Detailed Description
GeometryManager class.
Handle a user plugin in charge of loading the geometry in the framework and providing access to it.
Member Function Documentation
geometry()
template<typename T > const T * marlin::GeometryManager::geometry () const inline
Get the underlying geometry handle Example:
// assume Gear geometry has been loaded
const gear::GearMgr* gearGeo = mgr->geometry<gear::GearMgr>() ;
// assume DD4hep geometry has been loaded
const dd4hep::Detector* dd4hepGeo = mgr->geometry<dd4hep::Detector>() ;
Referenced by marlin::ProcessorApi::gearDetector(), and marlin::ProcessorApi::isFirstEvent().
init()
void marlin::GeometryManager::init (const Application * app)
Initialize the geometry manager.
Load the geometry plugin service and create the geometry
Parameters
app the application from which to get settings
References app(), marlin::Application::createLogger(), marlin::Application::geometryParameters(), marlin::PluginManager::instance(), and isInitialized().
The documentation for this class was generated from the following files:
GeometryManager.h
GeometryManager.cc