Marlin: marlin::RandomSeedManager Class Reference
marlin::RandomSeedManager Class Reference
RandomSeedManager class.
#include <RandomSeedManager.h>
Public Types
typedef unsigned int SeedType
typedef std::hash< const void * > HashFunction
typedef HashFunction::argument_type HashArgument
typedef HashFunction::result_type HashResult
typedef std::unordered_set< HashResult > EntryList
typedef std::map< HashResult, SeedType > RandomSeedMap
typedef std::mt19937 RandomGenerator
typedef std::uniform_int_distribution< SeedType > RandomDistribution
Public Member Functions
RandomSeedManager (const RandomSeedManager &)=delete
RandomSeedManager & operator= (const RandomSeedManager &)=delete
RandomSeedManager (SeedType globalSeed=time(nullptr))
Constructor with global seed.
void addEntry (HashResult entry)
Add an entry to the random seed manager.
void addEntry (HashArgument arg)
Add an entry to the random seed manager.
std::unique_ptr< RandomSeedMap > generateRandomSeeds (const EVENT::LCEvent *const evt)
Generate a random seed map.
Static Public Attributes
static const SeedType MinSeed = 0
static const SeedType MaxSeed = std::numeric_limits<SeedType>::max()
Detailed Description
RandomSeedManager class.
Constructor & Destructor Documentation
RandomSeedManager()
marlin::RandomSeedManager::RandomSeedManager (SeedType globalSeed = time(nullptr))
Constructor with global seed.
Parameters
globalSeed the global seed
Member Function Documentation
addEntry() [1/2]
void marlin::RandomSeedManager::addEntry (HashResult entry)
Add an entry to the random seed manager.
Parameters
entry a hash ideintifying the entry
Referenced by addEntry(), and marlin::ProcessorApi::registerForRandomSeeds().
addEntry() [2/2]
void marlin::RandomSeedManager::addEntry (HashArgument arg)
Add an entry to the random seed manager.
Parameters
entry a hash ideintifying the entry
References addEntry().
generateRandomSeeds()
std::unique_ptr< RandomSeedManager::RandomSeedMap > marlin::RandomSeedManager::generateRandomSeeds (const EVENT::LCEvent *const evt)
Generate a random seed map.
Mainly used by the whiteboard to get random seeds which are local for a given event context
Parameters
evt the event source
The documentation for this class was generated from the following files:
RandomSeedManager.h
RandomSeedManager.cc