Marlin: marlin::Parametrized Class Reference
marlin::Parametrized Class Reference
Public Types
typedef std::shared_ptr< Parameter > ParameterPtr
typedef std::map< std::string, ParameterPtr > ParameterMap
typedef std::map< std::string, std::string > LCIOTypeMap
typedef ParameterMap::iterator iterator
typedef ParameterMap::const_iterator const_iterator
Public Member Functions
Parametrized (const Parametrized &)=delete
Parametrized & operator= (const Parametrized &)=delete
template<class T >
void registerParameter (const std::string &parameterName, const std::string &parameterDescription, T &parameter, const T &defaultVal, int setSize=0)
Register a steering variable.
template<class T >
void registerOptionalParameter (const std::string &parameterName, const std::string &parameterDescription, T &parameter, const T &defaultVal, int setSize=0)
Same as registerParameter except that the parameter is optional.
void registerInputCollection (const std::string &collectionType, const std::string &parameterName, const std::string &parameterDescription, std::string &parameter, const std::string &defaultVal, int setSize=0)
Specialization of registerParameter() for a parameter that defines an input collection - can be used fo checking the consistency of the steering file.
void registerInputCollections (const std::string &collectionType, const std::string &parameterName, const std::string &parameterDescription, std::vector< std::string > &parameter, const std::vector< std::string > &defaultVal, int setSize=0)
Specialization of registerParameter() for a parameter that defines one or several input collections - can be used fo checking the consistency of the steering file.
void registerOutputCollection (const std::string &collectionType, const std::string &parameterName, const std::string &parameterDescription, std::string &parameter, const std::string &defaultVal, int setSize=0)
Specialization of registerParameter() for a parameter that defines an output collection - can be used fo checking the consistency of the steering file.
bool parameterSet (const std::string &name)
Tests whether the parameter has been set in the steering file.
void clearParameters ()
Clear the parameter map.
void setParameters (std::shared_ptr< StringParameters > parameters)
Update the parameter map with the input parameters.
std::vector< std::string > parameterNames () const
Get the list of parameter names.
template<typename T >
T getParameter (const std::string &name) const
Get a parameter value.
std::string getLCIOInType (const std::string &colName) const
Return the LCIO input type for the collection colName - empty string if colName is not a registered collection name.
std::string getLCIOOutType (const std::string &colName) const
Return the LCIO output type for the collection colName - empty string if colName is not a registered collection name.
bool isInputCollectionName (const std::string &parameterName) const
True if the given parameter defines an LCIO input collection, i.e.
bool isOutputCollectionName (const std::string &parameterName) const
True if the given parameter defines an LCIO output collection.
iterator pbegin ()
Begin iterator to parameter map.
iterator pend ()
End iterator of parameter map.
const_iterator pbegin () const
Begin iterator to parameter map.
const_iterator pend () const
End iterator of parameter map.
Member Function Documentation
getParameter()
template<typename T > T marlin::Parametrized::getParameter (const std::string & name) const inline
Get a parameter value.
If the parameter exists, an attempt to cast the parameter type to the same type as it was registered is done. It it fails, an exception is thrown. If the parameter doesn't exists, an exception is thrown. If the parameter exists but is not set, the default value is returned.
Parameters
name the parameter name
isInputCollectionName()
bool marlin::Parametrized::isInputCollectionName (const std::string & parameterName) const
True if the given parameter defines an LCIO input collection, i.e.
the type has been defined with setLCIOInType().
Referenced by marlin::Processor::printDescriptionXML().
registerOptionalParameter()
template<class T > void marlin::Parametrized::registerOptionalParameter (const std::string & parameterName, const std::string & parameterDescription, T & parameter, const T & defaultVal, int setSize = 0) inline
Same as registerParameter except that the parameter is optional.
The value of the parameter will still be set to the default value, which is used to print an example steering line. Use parameterSet() to check whether it actually has been set in the steering file.
References marlin::Parameter::setSize().
Referenced by marlin::GeometryPlugin::GeometryPlugin(), marlin::LCIOOutputProcessor::newProcessor(), and marlin::Processor::Processor().
registerParameter()
template<class T > void marlin::Parametrized::registerParameter (const std::string & parameterName, const std::string & parameterDescription, T & parameter, const T & defaultVal, int setSize = 0) inline
Register a steering variable.
The default value has to be of the same type as the parameter, e.g.
float _cut ;
// ...
registerParameter("Cut", "cut...", _cut , float(3.141592)) ;
as implicit conversions don't work for templates.
The optional parameter setSize is used for formating the printout of parameters. This can be used if the parameter values are expected to come in sets of fixed size.
References marlin::Parameter::setSize().
Referenced by marlin::Processor::registerProcessorParameter().
setParameters()
void marlin::Parametrized::setParameters (std::shared_ptr< StringParameters > parameters)
Update the parameter map with the input parameters.
Parameters
parameters the input parameter list
Referenced by marlin::DataSourcePlugin::init().
The documentation for this class was generated from the following files:
Parameter.h
Parameter.cc