Marlin: marlin::DataSourcePlugin Class Reference
marlin::DataSourcePlugin Class Reference abstract
DataSourcePlugin class Responsible for reading/getting LCEvent and LCRunHeader in the framework for further processing.
#include <DataSourcePlugin.h>
Public Types
using EventFunction = std::function< void(std::shared_ptr< EVENT::LCEvent >)>
using RunHeaderFunction = std::function< void(std::shared_ptr< EVENT::LCRunHeader >)>
using Logger = Logging::Logger
Public Types inherited from marlin::Parametrized
typedef std::shared_ptr< Parameter > ParameterPtr
typedef std::map< std::string, ParameterPtr > ParameterMap
typedef std::map< std::string, std::string > LCIOTypeMap
typedef ParameterMap::iterator iterator
typedef ParameterMap::const_iterator const_iterator
Public Member Functions
DataSourcePlugin (const std::string &dstype)
Constructor.
void init (const Application *app)
Initialize the plugin using application parameters.
const std::string & type () const
Get the data source type.
const std::string & description () const
Get the data source description.
virtual void init ()=0
Initialize the plugin.
virtual bool readOne ()=0
Read one record from the input stream.
virtual void readAll ()
Read the full stream until the end See readOne() for details.
void onEventRead (EventFunction func)
Set the callback function to process on event read.
void onRunHeaderRead (RunHeaderFunction func)
Set the callback function to process on run header read.
Logger logger () const
Get the plugin logger.
Public Member Functions inherited from marlin::Parametrized
Parametrized (const Parametrized &)=delete
Parametrized & operator= (const Parametrized &)=delete
template<class T >
void registerParameter (const std::string &parameterName, const std::string &parameterDescription, T &parameter, const T &defaultVal, int setSize=0)
Register a steering variable.
template<class T >
void registerOptionalParameter (const std::string &parameterName, const std::string &parameterDescription, T &parameter, const T &defaultVal, int setSize=0)
Same as registerParameter except that the parameter is optional.
void registerInputCollection (const std::string &collectionType, const std::string &parameterName, const std::string &parameterDescription, std::string &parameter, const std::string &defaultVal, int setSize=0)
Specialization of registerParameter() for a parameter that defines an input collection - can be used fo checking the consistency of the steering file.
void registerInputCollections (const std::string &collectionType, const std::string &parameterName, const std::string &parameterDescription, std::vector< std::string > &parameter, const std::vector< std::string > &defaultVal, int setSize=0)
Specialization of registerParameter() for a parameter that defines one or several input collections - can be used fo checking the consistency of the steering file.
void registerOutputCollection (const std::string &collectionType, const std::string &parameterName, const std::string &parameterDescription, std::string &parameter, const std::string &defaultVal, int setSize=0)
Specialization of registerParameter() for a parameter that defines an output collection - can be used fo checking the consistency of the steering file.
bool parameterSet (const std::string &name)
Tests whether the parameter has been set in the steering file.
void clearParameters ()
Clear the parameter map.
void setParameters (std::shared_ptr< StringParameters > parameters)
Update the parameter map with the input parameters.
std::vector< std::string > parameterNames () const
Get the list of parameter names.
template<typename T >
T getParameter (const std::string &name) const
Get a parameter value.
std::string getLCIOInType (const std::string &colName) const
Return the LCIO input type for the collection colName - empty string if colName is not a registered collection name.
std::string getLCIOOutType (const std::string &colName) const
Return the LCIO output type for the collection colName - empty string if colName is not a registered collection name.
bool isInputCollectionName (const std::string &parameterName) const
True if the given parameter defines an LCIO input collection, i.e.
bool isOutputCollectionName (const std::string &parameterName) const
True if the given parameter defines an LCIO output collection.
iterator pbegin ()
Begin iterator to parameter map.
iterator pend ()
End iterator of parameter map.
const_iterator pbegin () const
Begin iterator to parameter map.
const_iterator pend () const
End iterator of parameter map.
Protected Member Functions
void processRunHeader (std::shared_ptr< EVENT::LCRunHeader > rhdr)
Must be called by daughter classes in readStream() to process an event in the framework.
void processEvent (std::shared_ptr< EVENT::LCEvent > event)
Must be called by daughter classes in readStream() to process an event in the framework.
Protected Attributes
std::string _description {"No description"}
< The data source description
Detailed Description
DataSourcePlugin class Responsible for reading/getting LCEvent and LCRunHeader in the framework for further processing.
Constructor & Destructor Documentation
DataSourcePlugin()
marlin::DataSourcePlugin::DataSourcePlugin (const std::string & dstype)
Constructor.
Parameters
dstype the data source plugin type
References marlin::Logging::createLogger().
Member Function Documentation
init()
void marlin::DataSourcePlugin::init (const Application * app)
Initialize the plugin using application parameters.
Parameters
app the application in which the plugin is running
References marlin::Application::createLogger(), marlin::Application::dataSourceParameters(), description(), init(), logger(), marlin::Parametrized::setParameters(), and type().
onEventRead()
void marlin::DataSourcePlugin::onEventRead (EventFunction func)
Set the callback function to process on event read.
Parameters
func the callback function
onRunHeaderRead()
void marlin::DataSourcePlugin::onRunHeaderRead (RunHeaderFunction func)
Set the callback function to process on run header read.
Parameters
func the callback function
processEvent()
void marlin::DataSourcePlugin::processEvent (std::shared_ptr< EVENT::LCEvent > event) protected
Must be called by daughter classes in readStream() to process an event in the framework.
Parameters
event the event to process
processRunHeader()
void marlin::DataSourcePlugin::processRunHeader (std::shared_ptr< EVENT::LCRunHeader > rhdr) protected
Must be called by daughter classes in readStream() to process an event in the framework.
Parameters
event the event to process
readOne()
virtual bool marlin::DataSourcePlugin::readOne () pure virtual
Read one record from the input stream.
Users must call processRunHeader() or processEvent() to forward it to the framework. Returns true on success. If the end of the stream is reached, return false.
Implemented in marlin::LCIOFileSource, and marlin::StdHepFileSource.
Referenced by readAll().
The documentation for this class was generated from the following files:
DataSourcePlugin.h
DataSourcePlugin.cc