Marlin: marlin::concurrency::PEPScheduler Class Reference
marlin::concurrency::PEPScheduler Class Reference
PEPScheduler class Parallel Event Processing Scheduler.
#include <PEPScheduler.h>
Public Types
using ConditionsMap = std::map< std::string, std::string >
using InputType = std::shared_ptr< EVENT::LCEvent >
using OutputType = WorkerOutput
using WorkerPool = ThreadPool< InputType, OutputType >
using Logger = Logging::Logger
using ProcessorSequence = std::shared_ptr< SuperSequence >
using PushResultList = std::vector< WorkerPool::PushResult >
using EventList = std::vector< std::shared_ptr< EVENT::LCEvent > >
using Clock = std::chrono::steady_clock
using TimePoint = std::chrono::steady_clock::time_point
Public Member Functions
void init (Application *app) override
Initialize the scheduler with app parameters.
void end () override
Terminate the scheduler activites Cleanup memory, etc ...
void processRunHeader (std::shared_ptr< EVENT::LCRunHeader > rhdr)
Process a run header.
void pushEvent (std::shared_ptr< EVENT::LCEvent > event) override
Push a new event to the scheduler for processing.
void popFinishedEvents (std::vector< std::shared_ptr< EVENT::LCEvent >> &events) override
Retrieve finished events from the scheduler.
std::size_t freeSlots () const override
Get the number of free event slots.
Detailed Description
PEPScheduler class Parallel Event Processing Scheduler.
Implements the scheduling of parallel inter-event processing.
A set of N worker threads are allocated at startup within a thread pool. Every time a new event is pushed in the scheduler, the event is queued in the thread pool for further processing. Note that this operation can fail if the thread pool queue is full. Use freeSlots() to know how many slots are free in the thread pool queue and avoid unexpected exceptions.
Member Function Documentation
init()
void marlin::concurrency::PEPScheduler::init (Application * app) override virtual
Initialize the scheduler with app parameters.
Parameters
app the application in which the scheduler runs
Implements marlin::IScheduler.
References marlin::Application::createLogger(), and marlin::clock::now().
popFinishedEvents()
void marlin::concurrency::PEPScheduler::popFinishedEvents (std::vector< std::shared_ptr< EVENT::LCEvent >> & events) override virtual
Retrieve finished events from the scheduler.
Parameters
events the list of event to retrieve
Implements marlin::IScheduler.
processRunHeader()
void marlin::concurrency::PEPScheduler::processRunHeader (std::shared_ptr< EVENT::LCRunHeader > rhdr) virtual
Process a run header.
Parameters
rhdr the run header to process
Implements marlin::IScheduler.
References marlin::clock::now().
pushEvent()
void marlin::concurrency::PEPScheduler::pushEvent (std::shared_ptr< EVENT::LCEvent > event) override virtual
Push a new event to the scheduler for processing.
Parameters
event the event to push
Implements marlin::IScheduler.
The documentation for this class was generated from the following files:
PEPScheduler.h
PEPScheduler.cc