Marlin: marlin::Processor Class Reference
marlin::Processor Class Reference abstract
Processor class.
#include <Processor.h>
Public Types
enum RuntimeOption { Critical, RuntimeOption::Clone }
RuntimeOption enumerator.
using RuntimeOptions = std::map< RuntimeOption, bool >
Public Types inherited from marlin::Parametrized
typedef std::shared_ptr< Parameter > ParameterPtr
typedef std::map< std::string, ParameterPtr > ParameterMap
typedef std::map< std::string, std::string > LCIOTypeMap
typedef ParameterMap::iterator iterator
typedef ParameterMap::const_iterator const_iterator
Public Member Functions
Processor (const std::string &typeName)
Constructor.
virtual Processor * newProcessor ()=0
Return a new instance of the processor (factory method)
virtual void init ()
Initialize the processor.
virtual void processRunHeader (EVENT::LCRunHeader *)
Process a run header (start of run) Called for every run, e.g.
virtual void processEvent (EVENT::LCEvent *)
Process an input event.
virtual void check (EVENT::LCEvent *)
Called for every event - right after processEvent() has been called for this processor.
virtual void end ()
Terminate the processor.
virtual const std::string & type () const
Return type name for the processor (as set in constructor).
virtual const std::string & name () const
Return the name of this processor.
virtual const std::string & logLevelName () const
Return the name of the local verbosity level of this processor - "" if not set.
virtual std::shared_ptr< StringParameters > parameters () const
Return the parameters defined for this Processor.
virtual void printDescription () const
Print information about this processor in ASCII steering file format.
virtual void printDescriptionXML (std::ostream &stream=std::cout) const
Print information about this processor in XML steering file format.
template<class T >
void printParameters () const
Print the parameters and their values depending on the given verbosity level.
void printParameters () const
Print the parameters and their values with verbosity level MESSAGE.
const std::string & description () const
Description of processor.
std::pair< bool, bool > getForcedRuntimeOption (RuntimeOption option) const
Get the forced runtime option settings.
void baseInit (Application *application)
Sets the registered steering parameters before calling init()
void setParameters (std::shared_ptr< StringParameters > parameters)
Initialize the parameters.
template<class T >
void message (const std::ostream &m) const
Public Member Functions inherited from marlin::Parametrized
Parametrized (const Parametrized &)=delete
Parametrized & operator= (const Parametrized &)=delete
template<class T >
void registerParameter (const std::string &parameterName, const std::string &parameterDescription, T &parameter, const T &defaultVal, int setSize=0)
Register a steering variable.
template<class T >
void registerOptionalParameter (const std::string &parameterName, const std::string &parameterDescription, T &parameter, const T &defaultVal, int setSize=0)
Same as registerParameter except that the parameter is optional.
void registerInputCollection (const std::string &collectionType, const std::string &parameterName, const std::string &parameterDescription, std::string &parameter, const std::string &defaultVal, int setSize=0)
Specialization of registerParameter() for a parameter that defines an input collection - can be used fo checking the consistency of the steering file.
void registerInputCollections (const std::string &collectionType, const std::string &parameterName, const std::string &parameterDescription, std::vector< std::string > &parameter, const std::vector< std::string > &defaultVal, int setSize=0)
Specialization of registerParameter() for a parameter that defines one or several input collections - can be used fo checking the consistency of the steering file.
void registerOutputCollection (const std::string &collectionType, const std::string &parameterName, const std::string &parameterDescription, std::string &parameter, const std::string &defaultVal, int setSize=0)
Specialization of registerParameter() for a parameter that defines an output collection - can be used fo checking the consistency of the steering file.
bool parameterSet (const std::string &name)
Tests whether the parameter has been set in the steering file.
void clearParameters ()
Clear the parameter map.
void setParameters (std::shared_ptr< StringParameters > parameters)
Update the parameter map with the input parameters.
std::vector< std::string > parameterNames () const
Get the list of parameter names.
template<typename T >
T getParameter (const std::string &name) const
Get a parameter value.
std::string getLCIOInType (const std::string &colName) const
Return the LCIO input type for the collection colName - empty string if colName is not a registered collection name.
std::string getLCIOOutType (const std::string &colName) const
Return the LCIO output type for the collection colName - empty string if colName is not a registered collection name.
bool isInputCollectionName (const std::string &parameterName) const
True if the given parameter defines an LCIO input collection, i.e.
bool isOutputCollectionName (const std::string &parameterName) const
True if the given parameter defines an LCIO output collection.
iterator pbegin ()
Begin iterator to parameter map.
iterator pend ()
End iterator of parameter map.
const_iterator pbegin () const
Begin iterator to parameter map.
const_iterator pend () const
End iterator of parameter map.
Protected Member Functions
void forceRuntimeOption (RuntimeOption option, bool value)
Force the runtime option to a given boolean value.
template<class T >
void registerProcessorParameter (const std::string &parameterName, const std::string &parameterDescription, T &parameter, const T &defaultVal, int setSize=0)
Alias function to Parametrized::registerParameter.
template<class T >
void message (const std::string &m) const
Print message according to verbosity level of the templated parameter (one of DEBUG, MESSAGE, WARNING, ERROR) and the global parameter "Verbosity".
template<class T >
void message (const std::basic_ostream< char, std::char_traits< char > > &m) const
Same as message(const std::string& message) except that it allows the output of more complex messages in the argument using the log() method, e.g.
template<class T >
Logging::StreamType log () const
Logging function Example usage:
const Application & app () const
Get the application in which the processor is running Throws if the application is not set.
Application & app ()
Get the application in which the processor is running Throws if the application is not set.
Protected Attributes
std::string _description {""}
The processor description.
std::string _typeName {""}
The processor type.
std::string _processorName {""}
The processor name.
std::shared_ptr< StringParameters > _parameters {nullptr}
The processor parameters.
std::string _logLevelName {}
The processor logger level.
Friends
class ProcessorApi
Detailed Description
Processor class.
Base class for Marlin processors. Users can optionaly overwrite the following methods:
init, processRun, processEvent and end.
Use registerProcessorParameter to define all parameters that the module uses. Registered parameters are filled automatically before init() is called. With MyAplication -l you can print a list of available processors including the steering parameters they use/need.
With MyAplication -x you can print an example XML steering file for all known processors.
See also
init
processRun
processEvent
end
Author
F. Gaede, DESY
Version
Id
Processor.h,v 1.38 2008-06-26 10:25:36 gaede Exp
Member Enumeration Documentation
RuntimeOption
enum marlin::Processor::RuntimeOption strong
RuntimeOption enumerator.
Enumerator
Clone
Whether the processor has to be executed in a critical section.
Whether the processor must be cloned in each thread worker
Constructor & Destructor Documentation
Processor()
marlin::Processor::Processor (const std::string & typeName)
Constructor.
Subclasses need to call this in their default constructor.
Parameters
typeName the processor type
References _logLevelName, _typeName, marlin::Logging::createLogger(), marlin::PluginManager::instance(), newProcessor(), marlin::Parametrized::registerOptionalParameter(), marlin::PluginManager::registerPlugin(), and type().
Member Function Documentation
check()
virtual void marlin::Processor::check (EVENT::LCEvent *) inline virtual
Called for every event - right after processEvent() has been called for this processor.
Use to check processing and/or produce check plots.
Reimplemented in marlin::TestProcessor.
end()
virtual void marlin::Processor::end () inline virtual
Terminate the processor.
Called after data processing for clean up in the inverse order of the init() method so that resources allocated in the first processor also will be available for all following processors.
Reimplemented in marlin::LCIOOutputProcessor, marlin::TestProcessor, and marlin::Statusmonitor.
References app(), baseInit(), description(), forceRuntimeOption(), getForcedRuntimeOption(), log(), logLevelName(), message(), name(), parameters(), printDescription(), printDescriptionXML(), printParameters(), registerProcessorParameter(), setParameters(), and type().
forceRuntimeOption()
void marlin::Processor::forceRuntimeOption (RuntimeOption option, bool value) protected
Force the runtime option to a given boolean value.
Depending on the implementation of your processor, setting one of the runtime option might be a necessity. For example, you handle a lot of data in your processor members that you don't want to duplicate. In this case you should call in the constructor
forceRuntimeOption(Processor::RuntimeOption::Clone, false) ;
The code contained in processEvent() might also not be thread safe. In this case you can ask the Marlin framework to call the processEvent() method in a critical section (using std::mutex). Do to so, call:
forceRuntimeOption(RuntimeOption::Critical, true) ;
If a runtime option is forced in the code and the steering file tries to overwrite it, an exception will be raised.
Note that this method must be called in user processor constructor to ensure it is correctly handled by the framework at configuration time.
Parameters
option the runtime option to force
value the boolean value to set
Referenced by end(), marlin::MemoryMonitorProcessor::MemoryMonitorProcessor(), marlin::Statusmonitor::newProcessor(), and marlin::LCIOOutputProcessor::newProcessor().
getForcedRuntimeOption()
std::pair< bool, bool > marlin::Processor::getForcedRuntimeOption (RuntimeOption option) const
Get the forced runtime option settings.
The pair returned contains two boolean values:
first: whether the option appears in the forced options
second: if first is true, then contains the option flag
Parameters
option the runtime option to get
Referenced by end().
init()
virtual void marlin::Processor::init () inline virtual
Initialize the processor.
Called at the begin of the job before anything is read. Use to initialize the processor, e.g. book histograms.
Reimplemented in marlin::SimpleFastMCProcessor, marlin::LCIOOutputProcessor, marlin::MemoryMonitorProcessor, marlin::TestProcessor, marlin::EventSelectorProcessor, marlin::Statusmonitor, and marlin::CPUCrunchingProcessor.
Referenced by baseInit().
log()
template<class T > Logging::StreamType marlin::Processor::log () const inline protected
Logging function Example usage:
log<DEBUG>() << "This is a DEBUG message" << std::endl ;
References _processorName, and setParameters().
Referenced by marlin::ProcessorApi::abort(), end(), and marlin::ProcessorApi::skipCurrentEvent().
message() [1/2]
template<class T > void marlin::Processor::message (const std::string & m) const inline protected
Print message according to verbosity level of the templated parameter (one of DEBUG, MESSAGE, WARNING, ERROR) and the global parameter "Verbosity".
If Marlin is compiled w/o debug mode ($MARLINDEBUG not set) then DEBUG messages will be ignored completely at compile time, i.e. no output (and code!) will be generated, regardless of the value of the "Verbosity" parameter. This is useful in order to save CPU time in production mode.
Every line of the output string will be prepended by the verbosity level of the message and the processor name, e.g:
  [ MESSAGE "MyTestProcessor" ]  processing event 42 in run 4711
Use this method for simple strings. In order to use more complex messages, including numbers, use:
See also
void message(const std::basic_ostream<char, std::char_traits<char> >& m)
Deprecated:
Referenced by end().
message() [2/2]
template<class T > void marlin::Processor::message (const std::basic_ostream< char, std::char_traits< char > > & m) const inline protected
Same as message(const std::string& message) except that it allows the output of more complex messages in the argument using the log() method, e.g.
:
message<MESSAGE>(log()
                  << " processing event " << evt->getEventNumber()
                  << "  in run "          << evt->getRunNumber()
                  ) ;
Deprecated:
See also
void message(const std::string& message)
std::stringstream& log()
processEvent()
virtual void marlin::Processor::processEvent (EVENT::LCEvent *) inline virtual
Process an input event.
Called for every event - the working horse.
Reimplemented in marlin::SimpleFastMCProcessor, marlin::LCIOOutputProcessor, marlin::TestProcessor, marlin::Statusmonitor, marlin::MemoryMonitorProcessor, marlin::EventSelectorProcessor, and marlin::CPUCrunchingProcessor.
processRunHeader()
virtual void marlin::Processor::processRunHeader (EVENT::LCRunHeader *) inline virtual
Process a run header (start of run) Called for every run, e.g.
overwrite to initialize run dependent histograms.
Reimplemented in marlin::LCIOOutputProcessor, marlin::TestProcessor, and marlin::Statusmonitor.
The documentation for this class was generated from the following files:
Processor.h
Processor.cc