Marlin: marlin::Application Class Reference
marlin::Application Class Reference
Application class Base application interface for running a Marlin application.
#include <Application.h>
Public Types
using CmdLineArguments = std::vector< std::string >
using Logger = Logging::Logger
using Scheduler = std::shared_ptr< IScheduler >
using EventList = std::vector< std::shared_ptr< EVENT::LCEvent > >
using DataSource = std::shared_ptr< DataSourcePlugin >
using ConditionsMap = std::map< std::string, std::string >
Public Member Functions
void init (int argc, char **argv)
Initialize the application.
void run ()
Run the application.
void printUsage () const
Print command line usage.
void printBanner (std::ostream &out=std::cout) const
Print the Marlin banner.
const std::string & program () const
Get the program name.
const CmdLineArguments & arguments () const
Get the command line arguments.
std::shared_ptr< StringParameters > globalParameters () const
Get the global section parameters.
std::shared_ptr< StringParameters > geometryParameters () const
Get the geometry section parameters.
std::shared_ptr< StringParameters > dataSourceParameters () const
Get the data source section parameters.
std::shared_ptr< StringParameters > processorParameters (const std::string &name) const
Get the processor parameters.
std::shared_ptr< StringParameters > constants () const
Get the XML constants.
std::vector< std::string > activeProcessors () const
Get the active processor list.
std::vector< std::string > processorConditions () const
Get the active processor conditions list.
bool isInitialized () const
Whether the application has been initialized.
Logger logger () const
Get the application logger instance.
Logger createLogger (const std::string &name) const
Create a new logger instance.
const GeometryManager & geometryManager () const
Get the geometry manager.
const RandomSeedManager & randomSeedManager () const
Get the random seed manager.
RandomSeedManager & randomSeedManager ()
Get the random seed manager.
void setScheduler (Scheduler scheduler)
Set the scheduler instance to use in this application.
Protected Member Functions
std::shared_ptr< IParser > parser () const
Get the parser instance.
Protected Attributes
CmdLineArguments _filteredArguments {}
The arguments from main function after command line arguments have been removed.
GeometryManager _geometryMgr {}
The geometry manager.
RandomSeedManager _randomSeedMgr {}
The random seed manager.
LoggerManager _loggerMgr {}
The logger manager.
Detailed Description
Application class Base application interface for running a Marlin application.
See daughter classes for details.
Member Function Documentation
createLogger()
Application::Logger marlin::Application::createLogger (const std::string & name) const
Create a new logger instance.
If the logger manager is initialized, the logger will share the same sinks as the main logger, else a fresh new logger is created.
Parameters
name the logger name
Referenced by marlin::Processor::baseInit(), marlin::SimpleScheduler::init(), marlin::GeometryManager::init(), marlin::DataSourcePlugin::init(), marlin::concurrency::PEPScheduler::init(), and marlin::GeometryPlugin::print().
init()
void marlin::Application::init (int argc, char ** argv)
Initialize the application.
Parameters
argc argc from main function
argv argv from main function
printBanner()
void marlin::Application::printBanner (std::ostream & out = std::cout) const
Print the Marlin banner.
Parameters
out the out stream for printout
processorParameters()
std::shared_ptr< StringParameters > marlin::Application::processorParameters (const std::string & name) const
Get the processor parameters.
Parameters
name the processor name
Referenced by marlin::concurrency::PEPScheduler::end(), and marlin::SimpleScheduler::init().
setScheduler()
void marlin::Application::setScheduler (Scheduler scheduler)
Set the scheduler instance to use in this application.
Must be called before init(argc, argv)
Parameters
scheduler the sceduler instance to use
The documentation for this class was generated from the following files:
Application.h
Application.cc