Marlin: marlin::XMLTools Class Reference
marlin::XMLTools Class Reference
XMLTools Various helper function for XML files.
#include <XMLTools.h>
Static Public Member Functions
static void dumpRegisteredProcessors (std::ostream &stream)
Dump the registered processors in the ostream.
static void dumpRegisteredProcessors (const std::string &fname)
Dump the registered processors in the XML file.
Detailed Description
XMLTools Various helper function for XML files.
Member Function Documentation
dumpRegisteredProcessors() [1/2]
void marlin::XMLTools::dumpRegisteredProcessors (std::ostream & stream) static
Dump the registered processors in the ostream.
Parameters
stream the output stream
References marlin::PluginManager::instance(), and marlin::Processor::printDescriptionXML().
Referenced by dumpRegisteredProcessors().
dumpRegisteredProcessors() [2/2]
void marlin::XMLTools::dumpRegisteredProcessors (const std::string & fname) static
Dump the registered processors in the XML file.
Parameters
fname the output steering file name
References dumpRegisteredProcessors().
The documentation for this class was generated from the following files:
XMLTools.h
XMLTools.cc