Marlin: marlin::ErrorOfSigma Class Reference
marlin::ErrorOfSigma Class Reference
Small helper class that computes the lower and upper error of sigma assuming a normal distribution, i.e.
#include <ErrorOfSigma.h>
Public Member Functions
ErrorOfSigma (unsigned n)
C'tor takes the number of measured values.
virtual ~ErrorOfSigma ()
Virtual d'tor.
double lowerError (double sigma)
The lower error of sigma.
double upperError (double sigma)
The upper error of sigma.
Protected Member Functions
virtual double getChiSquaredPlus ()
Returns the chisquared value with P(chisquared) == 0.84.
virtual double getChiSquaredMinus ()
Returns the chisquared value with P(chisquared) == 0.16.
Protected Attributes
unsigned _n
The number of degrees of freedom.
Detailed Description
Small helper class that computes the lower and upper error of sigma assuming a normal distribution, i.e.
sigma has been computed as sigma = 1. / (n-1) * SUM_i_n(x_i - a_i)**2.
Author
F. Gaede, DESY
Version
Id
ErrorOfSigma.h,v 1.2 2005-10-11 12:56:28 gaede Exp
Constructor & Destructor Documentation
~ErrorOfSigma()
virtual marlin::ErrorOfSigma::~ErrorOfSigma () inline virtual
Virtual d'tor.
References getChiSquaredMinus(), getChiSquaredPlus(), lowerError(), and upperError().
The documentation for this class was generated from the following files:
ErrorOfSigma.h
ErrorOfSigma.cc