Marlin: marlin::ProcessorApi Class Reference
marlin::ProcessorApi Class Reference
ProcessorApi class.
#include <ProcessorApi.h>
Static Public Member Functions
static void registerForRandomSeeds (Processor *const proc)
Register the processor to get random seeds.
static unsigned int getRandomSeed (const Processor *const proc, EVENT::LCEvent *event)
Get a random seed from the event.
static void setReturnValue (const Processor *const proc, EVENT::LCEvent *event, bool value)
Set the processor return value.
static void setReturnValue (const Processor *const proc, EVENT::LCEvent *event, const std::string &name, bool value)
Set the named processor return value.
static bool isFirstEvent (EVENT::LCEvent *event)
Whether the event is the first event to be processed.
static const gear::GearMgr * gearDetector (const Processor *const proc)
Get the geometry instance as gear geometry.
static void skipCurrentEvent (const Processor *const proc)
Notify the application to skip the current event processing and go directly to the next event by skipping next processors in the sequence.
static void abort (const Processor *const proc, const std::string &reason)
Abort program execution properly.
Detailed Description
ProcessorApi class.
Provide a static API for processors to make high level calls. For example, to register your processor for random seeds:
// in your processor init() function
ProcessorApi::registerForRandomSeeds(this) ;
Member Function Documentation
abort()
void marlin::ProcessorApi::abort (const Processor *const proc, const std::string & reason) static
Abort program execution properly.
Parameters
proc the processor initiating the abort call
reason the reason why the processor aborts the program
References marlin::Processor::log().
gearDetector()
const gear::GearMgr * marlin::ProcessorApi::gearDetector (const Processor *const proc) static
Get the geometry instance as gear geometry.
WARNING: The geometry must be initialized with the dedicated gear plugin, else the geometry cast will fail and an exception is thrown
Parameters
proc the processor accessing the geometry
References marlin::Processor::app(), marlin::GeometryManager::geometry(), and marlin::Application::geometryManager().
getRandomSeed()
unsigned int marlin::ProcessorApi::getRandomSeed (const Processor *const proc, EVENT::LCEvent * event) static
Get a random seed from the event.
Your processor must have been registered before hand using registerForRandomSeeds()
Parameters
proc the processor instance
event the current event from which to get random seeds
Referenced by marlin::CPUCrunchingProcessor::processEvent().
isFirstEvent()
bool marlin::ProcessorApi::isFirstEvent (EVENT::LCEvent * event) static
Whether the event is the first event to be processed.
WARNING! Use this method with caution in multi-threading mode. The first event is the first that has been pushed in the scheduler queue, maybe not the first one received in Processor::processEvent(). Don't rely on this method to initialize data on first event, but rather use the init() method for that purpose.
Parameters
event the event to test
References marlin::Processor::app(), marlin::GeometryManager::geometry(), and marlin::Application::geometryManager().
registerForRandomSeeds()
void marlin::ProcessorApi::registerForRandomSeeds (Processor *const proc) static
Register the processor to get random seeds.
Parameters
proc the processor to register
References marlin::RandomSeedManager::addEntry(), marlin::Processor::app(), and marlin::Application::randomSeedManager().
Referenced by marlin::CPUCrunchingProcessor::init().
setReturnValue() [1/2]
void marlin::ProcessorApi::setReturnValue (const Processor *const proc, EVENT::LCEvent * event, bool value) static
Set the processor return value.
Parameters
proc the processor instance
event the event to which the condition is attached
value the processor return value
setReturnValue() [2/2]
void marlin::ProcessorApi::setReturnValue (const Processor *const proc, EVENT::LCEvent * event, const std::string & name, bool value) static
Set the named processor return value.
Parameters
proc the processor instance
event the event to which the condition is attached
name the name of the return value
value the processor return value
skipCurrentEvent()
void marlin::ProcessorApi::skipCurrentEvent (const Processor *const proc) static
Notify the application to skip the current event processing and go directly to the next event by skipping next processors in the sequence.
Parameters
proc the processor instance initiating the call
References marlin::Processor::log().
The documentation for this class was generated from the following files:
ProcessorApi.h
ProcessorApi.cc