Marlin: marlin::clock Class Reference
marlin::clock Class Reference
clock class Provide a wrapper around a certain clock type in std to perform safe clock measurement in multi-threading environement
#include <Utils.h>
Public Types
using clock_type = std::chrono::steady_clock
using time_point = clock_type::time_point
using duration_rep = float
using pair = std::pair< duration_rep, duration_rep >
using nanoseconds = std::chrono::duration< duration_rep, std::nano >
using microseconds = std::chrono::duration< duration_rep, std::micro >
using milliseconds = std::chrono::duration< duration_rep, std::milli >
using seconds = std::chrono::duration< duration_rep >
using minutes = std::chrono::duration< duration_rep, std::ratio< 60 > >
Static Public Member Functions
static time_point now ()
Get the current time.
template<class unit = seconds>
static duration_rep elapsed_since (const time_point &since)
Get the elapsed time since a previous time point.
template<class unit = seconds>
static duration_rep time_difference (const time_point &older, const time_point &ealier)
Get the time difference between two time points.
template<class unit = seconds>
static void crunchFor (duration_rep crunchTime)
Crunch numbers for some time.
Detailed Description
clock class Provide a wrapper around a certain clock type in std to perform safe clock measurement in multi-threading environement
Member Function Documentation
crunchFor()
template<class unit = seconds> static void marlin::clock::crunchFor (duration_rep crunchTime) inline static
Crunch numbers for some time.
The template parameter specifies the unit
Parameters
crunchTime the time duration
References now().
elapsed_since()
template<class unit = seconds> static duration_rep marlin::clock::elapsed_since (const time_point & since) inline static
Get the elapsed time since a previous time point.
The template parameter 'unit' allows for casting the result to a specific unit (default seconds). Use the duration types defined in this class to get a correct calculation. The result is floating type.
Parameters
since an earlier time point
References now().
time_difference()
template<class unit = seconds> static duration_rep marlin::clock::time_difference (const time_point & older, const time_point & ealier) inline static
Get the time difference between two time points.
The template parameter 'unit' allows for casting the result to a specific unit (default seconds). Use the duration types defined in this class to get a correct calculation. The result is floating type. Example:
auto start = clock::now();
// do stuff
auto end = clock::now();
// get the time difference in milliseconds as a float
auto ms_spent = clock::time_difference<clock::milliseconds>(start, end);
Parameters
older the oldest time point
ealier the earliest time point
Referenced by marlin::concurrency::PEPScheduler::end().
The documentation for this class was generated from the following file:
Utils.h