Marlin: marlin::StringParameters Class Reference
marlin::StringParameters Class Reference
Simple parameters class for Marlin.
#include <StringParameters.h>
Public Member Functions
StringParameters (const StringParameters &sp)=default
void add (const std::string &key)
Add a parameter without value.
template<typename T >
void add (const std::string &key, const T &value)
Add a parameter with its value.
template<typename T >
void add (const std::string &key, const std::vector< T > &values)
Add a parameter with its values.
template<typename T >
void replace (const std::string &key, const T &value)
Replace a parameter with a new value.
template<typename T >
void replace (const std::string &key, const std::vector< T > &values)
Replace a parameter with a new values.
void erase (const std::string &key)
Erase a parameter.
bool isParameterSet (const std::string &key) const
Whether the parameter is set, meaning the entry already exists, but has no value.
bool exists (const std::string &key) const
Whether the parameter exists.
void unset (const std::string &key)
Unset a parameter.
void unset ()
Unset all parameters.
std::vector< std::string > keys () const
Get the parameter keys.
template<typename T >
T getValue (const std::string &key) const
Get a parameter value.
template<typename T >
std::vector< T > getValues (const std::string &key) const
Get parameter values.
template<typename T >
T getValue (const std::string &key, const T &fallback) const
Get a parameter value.
template<typename T >
std::vector< T > getValues (const std::string &key, const std::vector< T > &fallback) const
Get parameter values.
template<typename T >
void get (const std::string &key, T &value) const
Get a parameter value by reference.
template<typename T >
void get (const std::string &key, std::vector< T > &values) const
Get parameter values by reference.
Protected Attributes
ParametersMap _map {}
< The parameters map
Friends
std::ostream & operator<< (std::ostream &, const StringParameters &)
Detailed Description
Simple parameters class for Marlin.
Holds named parameters as string vectors.
Author
F. Gaede, DESY
R. Ete, DESY
Version
Id
StringParameters.h,v 1.5 2006-11-10 11:56:07 engels Exp
Member Function Documentation
add() [1/3]
void marlin::StringParameters::add (const std::string & key)
Add a parameter without value.
Does nothing if the parameter exists
Parameters
key the prameter key
References _map.
Referenced by add(), marlin::Parser::parse(), and replace().
add() [2/3]
template<typename T > void marlin::StringParameters::add (const std::string & key, const T & value) inline
Add a parameter with its value.
Note that the value is appended to the parameter list. To overwrite a parameter value, use replace() instead
Parameters
key the parameter key
value the parameter value
References _map, and add().
add() [3/3]
template<typename T > void marlin::StringParameters::add (const std::string & key, const std::vector< T > & values) inline
Add a parameter with its values.
Note that the values are appended to the parameter list. To overwrite a parameter value, use replace() instead
Parameters
key the parameter key
values the parameter values
References _map, and add().
erase()
void marlin::StringParameters::erase (const std::string & key)
Erase a parameter.
Parameters
key the parameter key
References _map.
Referenced by replace().
exists()
bool marlin::StringParameters::exists (const std::string & key) const
Whether the parameter exists.
Parameters
key the parameter key
References _map.
get() [1/2]
template<typename T > void marlin::StringParameters::get (const std::string & key, T & value) const inline
Get a parameter value by reference.
Parameters
key the parameter key
value the value to receive
References _map.
Referenced by marlin::Parser::parse(), marlin::XMLParser::parse(), and marlin::ParameterT< T >::setValue().
get() [2/2]
template<typename T > void marlin::StringParameters::get (const std::string & key, std::vector< T > & values) const inline
Get parameter values by reference.
Parameters
key the parameter key
values the values to receive
References _map.
getValue() [1/2]
template<typename T > T marlin::StringParameters::getValue (const std::string & key) const inline
Get a parameter value.
If the value doesn't exists, an exception is thrown.
Parameters
key the parameter key
References _map.
Referenced by marlin::Parser::parse().
getValue() [2/2]
template<typename T > T marlin::StringParameters::getValue (const std::string & key, const T & fallback) const inline
Get a parameter value.
If the value doesn't exists, the fallback value provided as second argument is returned
Parameters
key the parameter key
fallback the fallback value if not found
References _map.
getValues() [1/2]
template<typename T > std::vector< T > marlin::StringParameters::getValues (const std::string & key) const inline
Get parameter values.
If the values do not exists, an exception is thrown.
Parameters
key the parameter key
References _map.
getValues() [2/2]
template<typename T > std::vector< T > marlin::StringParameters::getValues (const std::string & key, const std::vector< T > & fallback) const inline
Get parameter values.
If the values do not exists, the fallback values provided as second argument is returned
Parameters
key the parameter key
fallback the fallback value if not found
References _map.
isParameterSet()
bool marlin::StringParameters::isParameterSet (const std::string & key) const
Whether the parameter is set, meaning the entry already exists, but has no value.
To check if a parameter exists, use exists() instead
Parameters
key the parameter key
References _map.
Referenced by marlin::ParameterT< T >::setValue().
replace() [1/2]
template<typename T > void marlin::StringParameters::replace (const std::string & key, const T & value) inline
Replace a parameter with a new value.
Parameters
key the parameter key
value the parameter value
References add(), and erase().
replace() [2/2]
template<typename T > void marlin::StringParameters::replace (const std::string & key, const std::vector< T > & values) inline
Replace a parameter with a new values.
Parameters
key the parameter key
values the parameter values
References add(), and erase().
unset()
void marlin::StringParameters::unset (const std::string & key)
Unset a parameter.
Parameters
key the parameter key
References _map.
The documentation for this class was generated from the following files:
StringParameters.h
StringParameters.cc