Marlin: marlin::GeometryPlugin Class Reference
marlin::GeometryPlugin Class Reference abstract
GeometryPlugin class Responsible for loading geometry in Marlin and providing access to it through the GeometryManager.
#include <GeometryPlugin.h>
Public Types
using Logger = Logging::Logger
Public Types inherited from marlin::Parametrized
typedef std::shared_ptr< Parameter > ParameterPtr
typedef std::map< std::string, ParameterPtr > ParameterMap
typedef std::map< std::string, std::string > LCIOTypeMap
typedef ParameterMap::iterator iterator
typedef ParameterMap::const_iterator const_iterator
Public Member Functions
GeometryPlugin (const GeometryPlugin &)=delete
GeometryPlugin & operator= (const GeometryPlugin &)=delete
virtual std::type_index typeIndex () const =0
Get a type index object from the geometry handle.
virtual void dumpGeometry () const =0
Dump the geometry in the console.
const std::string & description () const
Get the geometry description.
const std::string & type () const
Get the geometry type.
void print () const
Print the complete geometry plugin description.
Public Member Functions inherited from marlin::Parametrized
Parametrized (const Parametrized &)=delete
Parametrized & operator= (const Parametrized &)=delete
template<class T >
void registerParameter (const std::string &parameterName, const std::string &parameterDescription, T &parameter, const T &defaultVal, int setSize=0)
Register a steering variable.
template<class T >
void registerOptionalParameter (const std::string &parameterName, const std::string &parameterDescription, T &parameter, const T &defaultVal, int setSize=0)
Same as registerParameter except that the parameter is optional.
void registerInputCollection (const std::string &collectionType, const std::string &parameterName, const std::string &parameterDescription, std::string &parameter, const std::string &defaultVal, int setSize=0)
Specialization of registerParameter() for a parameter that defines an input collection - can be used fo checking the consistency of the steering file.
void registerInputCollections (const std::string &collectionType, const std::string &parameterName, const std::string &parameterDescription, std::vector< std::string > &parameter, const std::vector< std::string > &defaultVal, int setSize=0)
Specialization of registerParameter() for a parameter that defines one or several input collections - can be used fo checking the consistency of the steering file.
void registerOutputCollection (const std::string &collectionType, const std::string &parameterName, const std::string &parameterDescription, std::string &parameter, const std::string &defaultVal, int setSize=0)
Specialization of registerParameter() for a parameter that defines an output collection - can be used fo checking the consistency of the steering file.
bool parameterSet (const std::string &name)
Tests whether the parameter has been set in the steering file.
void clearParameters ()
Clear the parameter map.
void setParameters (std::shared_ptr< StringParameters > parameters)
Update the parameter map with the input parameters.
std::vector< std::string > parameterNames () const
Get the list of parameter names.
template<typename T >
T getParameter (const std::string &name) const
Get a parameter value.
std::string getLCIOInType (const std::string &colName) const
Return the LCIO input type for the collection colName - empty string if colName is not a registered collection name.
std::string getLCIOOutType (const std::string &colName) const
Return the LCIO output type for the collection colName - empty string if colName is not a registered collection name.
bool isInputCollectionName (const std::string &parameterName) const
True if the given parameter defines an LCIO input collection, i.e.
bool isOutputCollectionName (const std::string &parameterName) const
True if the given parameter defines an LCIO output collection.
iterator pbegin ()
Begin iterator to parameter map.
iterator pend ()
End iterator of parameter map.
const_iterator pbegin () const
Begin iterator to parameter map.
const_iterator pend () const
End iterator of parameter map.
Protected Member Functions
GeometryPlugin (const std::string &gtype)
Constructor.
virtual void loadGeometry ()=0
Load the geometry.
virtual const void * handle () const =0
Get a handle on the geometry instance.
virtual void destroy ()=0
Cleanup geometry.
const Application & app () const
Get the application in which the plugin has been created.
Protected Attributes
const std::string _type
The geometry type.
std::string _description {"No description"}
The geometry plugin description.
Logger _logger {nullptr}
The application logger.
bool _dumpGeometry {false}
Whether to dump the geometry on creation.
Friends
class GeometryManager
Detailed Description
GeometryPlugin class Responsible for loading geometry in Marlin and providing access to it through the GeometryManager.
Constructor & Destructor Documentation
GeometryPlugin()
marlin::GeometryPlugin::GeometryPlugin (const std::string & gtype) protected
Constructor.
To be called by sub classes
Parameters
gtype the geometry type
References _dumpGeometry, _logger, marlin::Logging::createLogger(), and marlin::Parametrized::registerOptionalParameter().
Member Function Documentation
description()
const std::string & marlin::GeometryPlugin::description () const inline
Get the geometry description.
Can be set by sub-classes in constructor (protected)
References _description.
Referenced by print().
print()
void marlin::GeometryPlugin::print () const
Print the complete geometry plugin description.
The geometry is dumped if the verbosity level is less than DEBUG5
References _dumpGeometry, _logger, _type, app(), marlin::Application::createLogger(), description(), dumpGeometry(), handle(), loadGeometry(), type(), and typeIndex().
The documentation for this class was generated from the following files:
GeometryPlugin.h
GeometryPlugin.cc