Marlin: marlin::TestProcessor Class Reference
marlin::TestProcessor Class Reference
Simple processor for testing.
Public Member Functions
Processor * newProcessor ()
Return a new instance of the processor (factory method)
void init ()
Called at the begin of the job before anything is read.
void processRunHeader (EVENT::LCRunHeader *run)
Called for every run.
void processEvent (EVENT::LCEvent *evt)
Called for every event - the working horse.
void check (EVENT::LCEvent *evt)
Called for every event - right after processEvent() has been called for this processor.
void end ()
Called after data processing for clean up.
Public Member Functions inherited from marlin::Processor
Processor (const std::string &typeName)
Constructor.
virtual const std::string & type () const
Return type name for the processor (as set in constructor).
virtual const std::string & name () const
Return the name of this processor.
virtual const std::string & logLevelName () const
Return the name of the local verbosity level of this processor - "" if not set.
virtual std::shared_ptr< StringParameters > parameters () const
Return the parameters defined for this Processor.
virtual void printDescription () const
Print information about this processor in ASCII steering file format.
virtual void printDescriptionXML (std::ostream &stream=std::cout) const
Print information about this processor in XML steering file format.
template<class T >
void printParameters () const
Print the parameters and their values depending on the given verbosity level.
void printParameters () const
Print the parameters and their values with verbosity level MESSAGE.
const std::string & description () const
Description of processor.
std::pair< bool, bool > getForcedRuntimeOption (RuntimeOption option) const
Get the forced runtime option settings.
void baseInit (Application *application)
Sets the registered steering parameters before calling init()
void setParameters (std::shared_ptr< StringParameters > parameters)
Initialize the parameters.
template<class T >
void message (const std::ostream &m) const
Public Member Functions inherited from marlin::Parametrized
Parametrized (const Parametrized &)=delete
Parametrized & operator= (const Parametrized &)=delete
template<class T >
void registerParameter (const std::string &parameterName, const std::string &parameterDescription, T &parameter, const T &defaultVal, int setSize=0)
Register a steering variable.
template<class T >
void registerOptionalParameter (const std::string &parameterName, const std::string &parameterDescription, T &parameter, const T &defaultVal, int setSize=0)
Same as registerParameter except that the parameter is optional.
void registerInputCollection (const std::string &collectionType, const std::string &parameterName, const std::string &parameterDescription, std::string &parameter, const std::string &defaultVal, int setSize=0)
Specialization of registerParameter() for a parameter that defines an input collection - can be used fo checking the consistency of the steering file.
void registerInputCollections (const std::string &collectionType, const std::string &parameterName, const std::string &parameterDescription, std::vector< std::string > &parameter, const std::vector< std::string > &defaultVal, int setSize=0)
Specialization of registerParameter() for a parameter that defines one or several input collections - can be used fo checking the consistency of the steering file.
void registerOutputCollection (const std::string &collectionType, const std::string &parameterName, const std::string &parameterDescription, std::string &parameter, const std::string &defaultVal, int setSize=0)
Specialization of registerParameter() for a parameter that defines an output collection - can be used fo checking the consistency of the steering file.
bool parameterSet (const std::string &name)
Tests whether the parameter has been set in the steering file.
void clearParameters ()
Clear the parameter map.
void setParameters (std::shared_ptr< StringParameters > parameters)
Update the parameter map with the input parameters.
std::vector< std::string > parameterNames () const
Get the list of parameter names.
template<typename T >
T getParameter (const std::string &name) const
Get a parameter value.
std::string getLCIOInType (const std::string &colName) const
Return the LCIO input type for the collection colName - empty string if colName is not a registered collection name.
std::string getLCIOOutType (const std::string &colName) const
Return the LCIO output type for the collection colName - empty string if colName is not a registered collection name.
bool isInputCollectionName (const std::string &parameterName) const
True if the given parameter defines an LCIO input collection, i.e.
bool isOutputCollectionName (const std::string &parameterName) const
True if the given parameter defines an LCIO output collection.
iterator pbegin ()
Begin iterator to parameter map.
iterator pend ()
End iterator of parameter map.
const_iterator pbegin () const
Begin iterator to parameter map.
const_iterator pend () const
End iterator of parameter map.
Protected Member Functions
void printEndMessage () const
Test method for const.
Protected Member Functions inherited from marlin::Processor
void forceRuntimeOption (RuntimeOption option, bool value)
Force the runtime option to a given boolean value.
template<class T >
void registerProcessorParameter (const std::string &parameterName, const std::string &parameterDescription, T &parameter, const T &defaultVal, int setSize=0)
Alias function to Parametrized::registerParameter.
template<class T >
void message (const std::string &m) const
Print message according to verbosity level of the templated parameter (one of DEBUG, MESSAGE, WARNING, ERROR) and the global parameter "Verbosity".
template<class T >
void message (const std::basic_ostream< char, std::char_traits< char > > &m) const
Same as message(const std::string& message) except that it allows the output of more complex messages in the argument using the log() method, e.g.
template<class T >
Logging::StreamType log () const
Logging function Example usage:
const Application & app () const
Get the application in which the processor is running Throws if the application is not set.
Application & app ()
Get the application in which the processor is running Throws if the application is not set.
Protected Attributes
int _nRun {0}
std::atomic_int _nEvt {0}
bool _doCalibration {false}
Protected Attributes inherited from marlin::Processor
std::string _description {""}
The processor description.
std::string _typeName {""}
The processor type.
std::string _processorName {""}
The processor name.
std::shared_ptr< StringParameters > _parameters {nullptr}
The processor parameters.
std::string _logLevelName {}
The processor logger level.
Additional Inherited Members
Public Types inherited from marlin::Processor
enum RuntimeOption { Critical, RuntimeOption::Clone }
RuntimeOption enumerator.
using RuntimeOptions = std::map< RuntimeOption, bool >
Public Types inherited from marlin::Parametrized
typedef std::shared_ptr< Parameter > ParameterPtr
typedef std::map< std::string, ParameterPtr > ParameterMap
typedef std::map< std::string, std::string > LCIOTypeMap
typedef ParameterMap::iterator iterator
typedef ParameterMap::const_iterator const_iterator
Detailed Description
Simple processor for testing.
Writes something to stdout for every callbackmethod.
Input - Prerequisites
none
Output
none
Author
F. Gaede, DESY
Version
Id
TestProcessor.h,v 1.7 2007-05-23 13:12:21 gaede Exp
Member Function Documentation
check()
void marlin::TestProcessor::check (EVENT::LCEvent *) virtual
Called for every event - right after processEvent() has been called for this processor.
Use to check processing and/or produce check plots.
Reimplemented from marlin::Processor.
Referenced by newProcessor().
init()
void marlin::TestProcessor::init () virtual
Called at the begin of the job before anything is read.
Use to initialize the processor, e.g. book histograms.
Reimplemented from marlin::Processor.
References marlin::Processor::name(), and marlin::Processor::parameters().
Referenced by newProcessor().
printEndMessage()
void marlin::TestProcessor::printEndMessage () const protected
Test method for const.
Referenced by end(), and newProcessor().
The documentation for this class was generated from the following file:
TestProcessor.cc