Marlin: marlin::SimpleParticleFactory Class Reference
marlin::SimpleParticleFactory Class Reference
Implementation of IRecoParticleFactory that implements the default behaviour as described in SimpleFastMCProcessor, i.e.
#include <SimpleParticleFactory.h>
Public Member Functions
virtual ~SimpleParticleFactory ()
Virtual d'tor.
virtual lcio::ReconstructedParticle * createReconstructedParticle (const lcio::MCParticle *mcp)
The actual factory method that creates a new ReconstructedParticle.
virtual void registerIFourVectorSmearer (IFourVectorSmearer *sm, FastMCParticleType type)
Register a particle four vector smearer for the given type.
virtual FastMCParticleType getParticleType (const lcio::MCParticle *mcp)
Returns the type of the MCParticle.
virtual void setMomentumCut (double mCut)
Helper function to determine the charge from the PDG (charge is missing from stdhep files)
Public Member Functions inherited from marlin::IRecoParticleFactory
virtual ~IRecoParticleFactory ()
Virtual d'tor.
Protected Attributes
std::vector< IFourVectorSmearer * > _smearingVec
double _momentumCut
Detailed Description
Implementation of IRecoParticleFactory that implements the default behaviour as described in SimpleFastMCProcessor, i.e.
have polar angle ranges with different resolutions for charged tracks, photons and neutral hadrons.
Author
F. Gaede, DESY
Version
Id
SimpleParticleFactory.h,v 1.3 2007-11-23 20:09:12 gaede Exp
Constructor & Destructor Documentation
~SimpleParticleFactory()
virtual marlin::SimpleParticleFactory::~SimpleParticleFactory () inline virtual
Virtual d'tor.
References createReconstructedParticle(), getParticleType(), registerIFourVectorSmearer(), and setMomentumCut().
Member Function Documentation
setMomentumCut()
void marlin::SimpleParticleFactory::setMomentumCut (double mCut) virtual
Helper function to determine the charge from the PDG (charge is missing from stdhep files)
Set the momentum cut in GeV - no particles are produced for ower momenta. Default is 0.1 eV.
Referenced by marlin::SimpleFastMCProcessor::init(), and ~SimpleParticleFactory().
The documentation for this class was generated from the following files:
SimpleParticleFactory.h
SimpleParticleFactory.cc