Marlin: marlin::LoggerManager Class Reference
marlin::LoggerManager Class Reference
LoggerManager class Responsible for configuring logger for a given application.
#include <LoggerManager.h>
Public Types
using Logger = Logging::Logger
Public Member Functions
LoggerManager (const LoggerManager &)=delete
LoggerManager & operator= (const LoggerManager &)=delete
LoggerManager ()
Constructor.
void init (const Application *app)
Initialize the manager and the manager using the application settings.
Logger mainLogger () const
Get the main logger instance (not the global one)
Logger createLogger (const std::string &name) const
Create a new logger instance.
void setLevel (const std::string &level)
Set the verbosity level of both the main and global loggers.
bool isInitialized () const
Whether the logger manager has been initialized.
Detailed Description
LoggerManager class Responsible for configuring logger for a given application.
Can possibly configure the global logger instance.
Member Function Documentation
createLogger()
LoggerManager::Logger marlin::LoggerManager::createLogger (const std::string & name) const
Create a new logger instance.
The logger shares the same sinks as the main logger
Parameters
name the logger name
References marlin::Logging::createLogger(), isInitialized(), and mainLogger().
init()
void marlin::LoggerManager::init (const Application * app)
Initialize the manager and the manager using the application settings.
Parameters
app the application
References marlin::Application::globalParameters(), mainLogger(), marlin::Application::program(), and setLevel().
setLevel()
void marlin::LoggerManager::setLevel (const std::string & level)
Set the verbosity level of both the main and global loggers.
Parameters
level the verbosity level to set
References mainLogger().
Referenced by init().
The documentation for this class was generated from the following files:
LoggerManager.h
LoggerManager.cc