name: Key4hep build

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 16 4 * * 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: ["release", "nightly"]
        image: ["alma9"]
        include:
          - build_type: "nightly"
            image: ubuntu24
    steps:
    - uses: actions/checkout@v5
    - uses: key4hep/key4hep-actions/key4hep-build@main
      with:
        build_type: ${{ matrix.build_type }}
        image: ${{ matrix.image }}
