name: keyh4ep
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - release: "sw.hsf.org/key4hep"
            CXX_STANDARD: 17
          - release: "sw-nightlies.hsf.org/key4hep"
            CXX_STANDARD: 20

    steps:
    - uses: actions/checkout@v3
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - uses: aidasoft/run-lcg-view@v4
      with:
        container: centos7
        view-path: /cvmfs/${{ matrix.release }}
        run: |
          mkdir build
          cd build
          echo "::group::Run CMake"
          cmake -GNinja \
            -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always -Werror " \
            -DCMAKE_CXX_STANDARD=${{ matrix.CXX_STANDARD }} \
            -DCMAKE_INSTALL_PREFIX=../install \
            ..
          echo "::endgroup::" && echo "::group::Build"
          ninja -k0
          echo "::endgroup::" && echo "::group::Run Tests"
          ctest --output-on-failure
          echo "::endgroup::" && echo "::group::Install"
          ninja install
